name: e_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # Remove charts_flutter dependency
  # charts_flutter: ^0.12.0
  equatable: ^2.0.7
  firebase_messaging: ^15.2.2
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
# assets:
